version: '3.9'

services:
 meetings-api:
  build: .
  ports:
   - "5000:80"
  depends_on:
   - ms-sql-server
 ms-sql-server:
  image: "mcr.microsoft.com/mssql/server"
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "Pa55w0rd2022"
  ports:
   - "1433:1433"
 